# Generated by Django 3.0.6 on 2020-06-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grards', '0002_auto_20200613_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('card_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlackGrard',
        ),
        migrations.DeleteModel(
            name='WhiteGrard',
        ),
    ]
