# Generated by Django 3.0.6 on 2020-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grards', '0003_auto_20200614_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CahCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('card_text', models.TextField()),
            ],
        ),
    ]
